language: node_js
sudo: required
dist: jessie
addons:
    firefox: latest
    apt:
        sources:
            - google-chrome
        packages:
            - google-chrome-stable
node_js:
    - '6.1'

before_script:
    - npm i -g

script:
    - ./travis-runner.sh

